"use strict";
var __cov_re6tCq9lemAmFeV_6PkEcg = (Function('return this'))();
if (!__cov_re6tCq9lemAmFeV_6PkEcg.__coverage__) { __cov_re6tCq9lemAmFeV_6PkEcg.__coverage__ = {}; }
__cov_re6tCq9lemAmFeV_6PkEcg = __cov_re6tCq9lemAmFeV_6PkEcg.__coverage__;
if (!(__cov_re6tCq9lemAmFeV_6PkEcg['src/js/releases.js'])) {
   __cov_re6tCq9lemAmFeV_6PkEcg['src/js/releases.js'] = {"path":"src/js/releases.js","s":{"1":1,"2":0,"3":1,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0,"11":0,"12":0},"b":{},"f":{"1":0,"2":0,"3":0,"4":0},"fnMap":{"1":{"name":"ReleaseService","line":3,"loc":{"start":{"line":3,"column":0},"end":{"line":3,"column":35}}},"2":{"name":"ReleasesCtrl","line":12,"loc":{"start":{"line":12,"column":0},"end":{"line":12,"column":38}}},"3":{"name":"(anonymous_3)","line":15,"loc":{"start":{"line":15,"column":8},"end":{"line":15,"column":22}}},"4":{"name":"(anonymous_4)","line":20,"loc":{"start":{"line":20,"column":8},"end":{"line":20,"column":23}}}},"statementMap":{"1":{"start":{"line":3,"column":0},"end":{"line":10,"column":1}},"2":{"start":{"line":4,"column":4},"end":{"line":9,"column":7}},"3":{"start":{"line":12,"column":0},"end":{"line":25,"column":1}},"4":{"start":{"line":13,"column":4},"end":{"line":13,"column":18}},"5":{"start":{"line":14,"column":4},"end":{"line":24,"column":7}},"6":{"start":{"line":17,"column":12},"end":{"line":17,"column":31}},"7":{"start":{"line":18,"column":12},"end":{"line":18,"column":31}},"8":{"start":{"line":22,"column":12},"end":{"line":22,"column":34}},"9":{"start":{"line":23,"column":12},"end":{"line":23,"column":28}},"10":{"start":{"line":27,"column":0},"end":{"line":27,"column":39}},"11":{"start":{"line":28,"column":0},"end":{"line":28,"column":42}},"12":{"start":{"line":30,"column":0},"end":{"line":32,"column":46}}},"branchMap":{}};
}
__cov_re6tCq9lemAmFeV_6PkEcg = __cov_re6tCq9lemAmFeV_6PkEcg['src/js/releases.js'];
function ReleaseService($resource){__cov_re6tCq9lemAmFeV_6PkEcg.f['1']++;__cov_re6tCq9lemAmFeV_6PkEcg.s['2']++;return $resource('https://api.github.com/repos/angular/protractor/tags',{},{get:{method:'GET',isArray:true}});}function ReleasesCtrl(ReleaseService){__cov_re6tCq9lemAmFeV_6PkEcg.f['2']++;__cov_re6tCq9lemAmFeV_6PkEcg.s['4']++;var vm=this;__cov_re6tCq9lemAmFeV_6PkEcg.s['5']++;ReleaseService.get({},function(data){__cov_re6tCq9lemAmFeV_6PkEcg.f['3']++;__cov_re6tCq9lemAmFeV_6PkEcg.s['6']++;vm.releases=data;__cov_re6tCq9lemAmFeV_6PkEcg.s['7']++;return vm.releases;},function(error){__cov_re6tCq9lemAmFeV_6PkEcg.f['4']++;__cov_re6tCq9lemAmFeV_6PkEcg.s['8']++;vm.error=error.data;__cov_re6tCq9lemAmFeV_6PkEcg.s['9']++;return vm.error;});}__cov_re6tCq9lemAmFeV_6PkEcg.s['10']++;ReleaseService.$inject=['$resource'];__cov_re6tCq9lemAmFeV_6PkEcg.s['11']++;ReleasesCtrl.$inject=['ReleaseService'];__cov_re6tCq9lemAmFeV_6PkEcg.s['12']++;angular.module('releases',['ngResource']).factory('ReleaseService',ReleaseService).controller('ReleasesCtrl',ReleasesCtrl);
